---
title: "MatsuokaDistribution"
output: rmarkdown::html_vignette
description: Learn how to use "MatsuokaDistribution" class object to estimate the production frontier
vignette: >
  %\VignetteIndexEntry{MatsuokaDistribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
library(matsuoka.frontier)
library(ggplot2)
library(Benchmarking)

data(milkProd)

N=nrow(milkProd)                #N=108
nc=milkProd$cows                #n cows
xc1=milkProd$vet/nc             #vet. expenses per cow (X)
x1=(xc1-min(xc1))/(max(xc1)-min(xc1))   #normalization 
xc2=milkProd$energy/nc          #energy expenses per cow (X)
x2=(xc2-min(xc2))/(max(xc2)-min(xc2))   #normalization
X=cbind(x1,x2)

y <- milkProd$milk/nc/10^3 

obj <- matsuoka.frontier::matsuoka3step(
  x = as.data.frame(X[,'x1']), y = y, g = "spline", lambda = 0.01
)

obj <- matsuoka.frontier::matsuoka3step(x = as.data.frame(X), y = y, g="gam")
str(obj)

plot.matsuoka3step <- function(x, type = "fit", ...) {
  if (type == "fit") {
    plot(x$x, x$y, pch = 19, col = "gray", main = "Observed vs Fitted", ...)
    lines(x$x, x$fitted, col = "blue", lwd = 2)
  } 
  else if (type == "residuals") {
    plot(x$fitted, x$residuals, pch = 19, col = "red",
         main = "Residuals vs Fitted", ...)
    abline(h = 0, lty = 2)
  } else {
    stop("Unknown plot type")
  }
}

plot(obj, "fit")

#plot.df <- data.frame(
#  x = obj$x,
#  y = obj$y,
#  frontier = obj$f_hat
#) 

# plot.df %>% ggplot(aes(x = x.x1, y = y)) +
#  geom_point(color="black") +
#  geom_line(aes(y = frontier), color="blue", size=1) +
#  theme_bw()
```
