name: r-cmd-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    env:
      R_REPOS: https://cran.r-project.org

    steps:
    - uses: actions/checkout@v3

    - name: set up r env
      uses: r-lib/actions/setup-r@v2

    - name: install system dependencies
      run: sudo apt-get install libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: install R package dependencies
      run: |
        Rscript -e 'options(repos = c(CRAN = Sys.getenv("R_REPOS"))); install.packages(c("remotes", "devtools", "testthat"))'
        Rscript -e 'options(repos = c(CRAN = Sys.getenv("R_REPOS"))); remotes::install_deps(dependencies = TRUE)'

    - name: check package 
      run: R CMD check --no-manual --as-cran .
